# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth', models.DateField(verbose_name='fecha de nacimiento de la mascota')),
                ('register', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/fotos/pets/', verbose_name=models.CharField(max_length=50))),
                ('estatus', models.BooleanField(default=True)),
                ('estate', models.BooleanField(default=True)),
                ('raza', models.CharField(max_length=50)),
                ('tipe', models.CharField(choices=[('A', 'Perro'), ('B', 'Gato')], default='A', max_length=1)),
                ('size', models.CharField(choices=[('A', 'Grande'), ('B', 'Mediano'), ('C', 'Peque')], default='A', max_length=1)),
                ('observations', models.TextField(blank=True, null=True, verbose_name='otros datos de importancia de la mascota')),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
